### ISSUE TITLE
Docker compose import needs to know what IP is assigned instead of default

### ISSUE THREAD

**Issue by Node815** [need4swede/Portall#1]
When importing from Docker compose, it assigns 127.0.0.1.  My particular case uses a separate host for Docker containers and it does not ask for the IP to disposition the import to.   Additionally, after importing as a test, it would not allow cross dragging to the correct Host IP.

**Comment by need4swede** [comment]
If no IP address is provided in an import, there's no way for Portall to know what IP to assign the ports to, so it will default to localhost [127.0.0.1].

You can edit this host by clicking the pencil icon in the top-right corner of the host panel, assign it a different IP and give it a different nickname.

**Comment by Node815** [comment]
In this case, if you allow the user to drag the newly mapped port to the desired block of ports for the IP you want it to, this would resolve the issue.  **OR**  Maybe adding a dialog near the input to drop down the list of IP's for the user select from to import it to may be easier.

**Comment by need4swede** [comment]
I think the problem you're referring to is a limitation of Portall that doesn't allow you to move the last port of an IP panel.

Here's an example:

Panel 1 has ports 1010, 2020
Panel 2 has port 3030

You can't move port 3030 from Panel 2 over to Panel 1, because that is the last remaining port of Panel 2, but you can move port 1010 or 2020 over to Panel 2. This is because IP panels aren't designed to exist independently of registered ports. I may change how I approach this in the future.

For now, you can click the '+' and create port 3030 on Panel 1 and then delete Panel 2 if you would like to 'move over' the last remaining port.
